main_url= "https://www.mcxindia.com/market-data/spot-market-price"
archive_button= 'today'
show_button= '//*[@id="btnShowArchive"]'
gold_dropdown_xpath1='//*[@id="ctl00_cph_InnerContainerRight_C004_ddlSymbols_Input"]'
select_gold_xpath2= '//*[@id="ctl00_cph_InnerContainerRight_C004_ddlSymbols_DropDown"]/div/ul/li[18]'
all_dropdown_xpath1='//*[@id="ctl00_cph_InnerContainerRight_C004_ddlLocationArchive_Input"]'
select_all_xpath2='//*[@id="ctl00_cph_InnerContainerRight_C004_ddlLocationArchive_DropDown"]/div/ul/li[1]'
session_dropdown_xpath1='//*[@id="cph_InnerContainerRight_C004_ddlSession"]'
selecting_session2_xpath2='//*[@id="cph_InnerContainerRight_C004_ddlSession"]/option[3]'
FROM_x1='//*[@id="txtFromDate"]'
FROM_year_x2='//select[@class="datepick-month-year"][@title="Change the year"]//option[text()="2023"]'
FROM_month_x3= '//select[@class="datepick-month-year"][@title="Change the month"]//option[text()="November"]'
FROM_date_x4='//a[text()="1"]'
TO_x1='//*[@id="txtToDate"]'
TO_year_x2='//select[@class="datepick-month-year"][@title="Change the year"]//option[text()="2024"]'
TO_year_x2='//select[@class="datepick-month-year"][@title="Change the month"]//option[text()="January"]'
TO_date_x4='//a[text()="24"]'